services:

  jaeger:
    image: 'jaegertracing/all-in-one:1.44'
    env_file:
      - .envs/jaeger.env
    networks:
      common-net:
        aliases:
          - common-jaeger
    ports:
      - 127.0.0.1:${JAEGER_PUBLISH_PORT:-16686}:16686
