networks:
  common-net:
    external: true

services:

  app:
    image: 'lv10-otel1-app:latest'
    build:
      context: ../
      dockerfile: docker/app/app.Dockerfile
      args:
        - TIMEZONE=${TIMEZONE}
        - UID=${UID}
        - GID=${GID}
    tty: true
    command:
      - apache2-foreground
    networks:
      - common-net
    env_file:
      - .envs/web.env
      - .envs/php-ini.env
    ports:
      - 8080:8080
    volumes:
      - ../:/var/www/html

  queue:
    image: 'lv10-otel1-app:latest'
    tty: true
    command:
      - php
      - artisan
      - queue:work
    stop_signal: SIGTERM
    networks:
      - common-net
    env_file:
      - .envs/php-ini.env
    volumes:
      - ../:/var/www/html
